-- Run in a dedicated Supabase project. Enable RLS before exposing any client keys.
create extension if not exists pgcrypto;
create type public.delivery_status as enum ('pending','fulfilled','revoked','failed');
create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, created_at timestamptz not null default now());
create table public.organization_members (organization_id uuid references public.organizations(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null check (role in ('owner','admin','member')), primary key (organization_id,user_id));
create table public.guardian_assessments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), submitted_by uuid not null references auth.users(id), consent_at timestamptz not null, score numeric(5,2), findings jsonb not null default '[]'::jsonb, created_at timestamptz not null default now());
create table public.delivery_ledger (id uuid primary key default gen_random_uuid(), idempotency_key text not null unique, organization_id uuid references public.organizations(id), user_id uuid references auth.users(id), sku text not null, provider text not null, provider_event_id text not null, status public.delivery_status not null default 'pending', payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), fulfilled_at timestamptz);
create table public.hydra_eyes_events (id uuid primary key default gen_random_uuid(), event_id uuid not null unique, occurred_at timestamptz not null, received_at timestamptz not null default now(), organization_id uuid references public.organizations(id), actor_id uuid references auth.users(id), event_type text not null check (event_type in ('view','click','checkout_started','purchase','assessment_submitted','report_generated','completion','status_flag')), source text not null, correlation_id text, properties jsonb not null default '{}'::jsonb);
alter table public.organizations enable row level security; alter table public.organization_members enable row level security; alter table public.guardian_assessments enable row level security; alter table public.delivery_ledger enable row level security; alter table public.hydra_eyes_events enable row level security;
create function public.is_org_member(target_org uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.organization_members where organization_id=target_org and user_id=auth.uid()) $$;
create policy "members read organizations" on public.organizations for select using (public.is_org_member(id));
create policy "members read assessments" on public.guardian_assessments for select using (public.is_org_member(organization_id));
create policy "members read deliveries" on public.delivery_ledger for select using (organization_id is null or public.is_org_member(organization_id));
create policy "members read telemetry" on public.hydra_eyes_events for select using (organization_id is null or public.is_org_member(organization_id));
-- Webhooks and telemetry are written by server-side service-role code only; never expose that key to the browser.
